config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  controller :pages do
    get '', action: :index, as: :pages
    get '(*ids)/add', action: :new, as: :new_page
    get '*ids/edit', action: :edit, as: :edit_page
    get '(*ids)', action: :show, as: :page
    post '(*ids)', action: :create
    put '*ids', action: :update
    patch '(*ids)', action: :update
  end
end

app/models/concerns/last_update_date.rb
module LastUpdateDate

  def last_update_date
    select(:updated_at).order(:updated_at).last.try(:updated_at)
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend LastUpdateDate

  acts_as_nested_set touch: true

  validates :title,
            :slug,
            :source_text, presence: true
  validates :slug, not_reserved_route: true, format: { with: /\A[а-яА-Яa-zA-Z0-9_]+\z/ }, uniqueness: true

  before_save :filter_source_text, if: Proc.new { |page| page.source_text_changed? }

  def to_param
    slug
  end

  private

  def filter_source_text
    self.text = TextFilter::Replacement.new.replace(source_text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :load_parent_page, only: [:new, :create]
  before_filter :load_page, only: [:show, :edit, :update]

  def new
    @page = @parent_page ? @parent_page.children.build : Page.new
  end

  def create
    @page = @parent_page ? @parent_page.children.build(page_create_params) : Page.new(page_create_params)
    if @page.save
      redirect_to page_path(ids: @page.self_and_ancestors.to_a)
    else
      render :new
    end
  end

  def update
    if @page.update_attributes(page_update_params)
      redirect_to page_path(ids: @page.self_and_ancestors.to_a)
    else
      render :edit
    end
  end

  private

  def page_create_params
    params.require(:page).permit(:title, :slug, :source_text)
  end

  def page_update_params
    params.require(:page).permit(:title, :source_text)
  end

  def load_parent_page
    @parent_page = load_nested_page(params[:ids])
  end

  def load_page
    @page = load_nested_page(params[:ids])
  end

  # Finds the page from slugs path.
  def load_nested_page(path)
    return unless path.present?

    slugs = path.split('/')
    page = Page.find_by!(slug: slugs.last)

    # Validation slugs path
    raise ActiveRecord::RecordNotFound, "Couldn't find Page: wrong ancestors" unless page.self_and_ancestors.map(&:slug) == slugs

    page
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  # Iterates over descendants elements with the current stack in the tree.
  # Stack includes current element and ancestors elements.
  # Also indicates level shift from the root element.
  # Example:
  #    each_nested_page_with_stack(Page.first) do |page, stack, shift|
  #
  def each_nested_page_with_stack(root_page = nil, &block)
    pages, stack = if root_page
                     [root_page.descendants, root_page.self_and_ancestors]
                   else
                     [Page.order(:lft), []]
                   end

    initial_depth = stack.length
    pages.each do |page|
      stack = stack.slice(0, page.depth)
      stack.push(page)
      block.call(page, stack, page.depth - initial_depth)
    end
  end
end

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    title
      = content_for?(:title) ? yield(:title) : 'PagesHierarchy'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'

  body
    .navbar.navbar-default.navbar-static-top
      .container
        = link_to 'PagesHierarchy', root_path, class: 'navbar-brand'

    .container
      .row.bottom-25
        .col-lg-12
          h2
            = yield(:page_header)
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

app/views/pages/_form.html.slim
= simple_form_for @page, url: page_path(ids: (@page.new_record? ? @parent_page : @page).try(:self_and_ancestors).to_a), wrapper: :horizontal_form do |f|
  = f.error_notification

  = f.input :title
  = f.input :slug if @page.new_record?
  = f.input :source_text, as: :text, label: Page.human_attribute_name(:text)

  = f.submit

app/views/pages/_nested_set.html.slim
- each_nested_page_with_stack(local_assigns[:root_page]) do |page, stack, shift|
  .row class='list-group-item' style="margin-left: #{30 * shift}px;"
    = page.title
    = link_to t('helpers.links.show'), page_path(ids: stack), class: 'btn btn-sm btn-primary pull-right'

app/views/pages/edit.html.slim
= content_for :page_header do
  = "Edit [#{@page.title}]"

= render partial: 'form'

app/views/pages/index.html.slim
- cache [:index, :pages, Page.last_update_date.try(:to_i)] do
  dl.dl-horizontal.left
    dt
      = t('helpers.actions')
    dd
      = link_to t('helpers.links.add'), new_page_path, class: 'btn btn-sm btn-primary'

  = render partial: 'nested_set'

app/views/pages/new.html.slim
= content_for :page_header do
  = @parent_page ? "New page to [#{@parent_page.title}]" : 'Add root page'

= render partial: 'form'

app/views/pages/show.html.slim
- cache [:show, @page] do
  dl.dl-horizontal.left
    dt
      = t('helpers.actions')
    dd
      = link_to t('helpers.links.add'), new_page_path(ids: @page.try(:self_and_ancestors).to_a), class: 'btn btn-sm btn-primary'
      | &nbsp;
      = link_to t('helpers.links.edit'), edit_page_path(ids: @page.self_and_ancestors.to_a), class: 'btn btn-sm btn-primary'
  dl.dl-horizontal.left
    dt
      = Page.human_attribute_name(:title)
    dd
      = @page.title
  dl.dl-horizontal.left
    dt
      = Page.human_attribute_name(:slug)
    dd
      = @page.slug
  dl.dl-horizontal.left
    dt
      = Page.human_attribute_name(:text)
    dd
      = @page.text.html_safe

  = render partial: 'nested_set', locals: { root_page: @page }